In [4]:
# Step 1: Imports
import torch
import torch.nn.functional as F

In [5]:
# Step 2: Create random Q,K,V
torch.manual_seed(0)
Q = torch.randn(2,4)
K = torch.randn(2,4)
V = torch.randn(2,4)

print("Q:\n",Q)
print("K:\n",K)
print("V:\n",V)


Q:
 tensor([[ 1.5410, -0.2934, -2.1788,  0.5684],
        [-1.0845, -1.3986,  0.4033,  0.8380]])
K:
 tensor([[-0.7193, -0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712,  0.1227]])
V:
 tensor([[-0.5663,  0.3731, -0.8920, -1.5091],
        [ 0.3704,  1.4565,  0.9398,  0.7748]])


In [6]:
# Step 3: Compute raw attention scores
scores = torch.matmul(Q, K.T)
print("Raw scores (QK^T):\n", scores)

Raw scores (QK^T):
 tensor([[ 0.4134,  0.7606],
        [ 1.2561, -0.9395]])


In [7]:
# Step 4: Scale scores
d_k = K.shape[-1]  # dimension of keys
scaled_scores = scores / torch.sqrt(torch.tensor(d_k, dtype=torch.float32))
print("Scaled scores:\n", scaled_scores)

Scaled scores:
 tensor([[ 0.2067,  0.3803],
        [ 0.6280, -0.4697]])


In [8]:
# Step 5: Softmax to get attention weights
attn_weights = F.softmax(scaled_scores, dim=-1)
print("Attention weights:\n", attn_weights)

Attention weights:
 tensor([[0.4567, 0.5433],
        [0.7498, 0.2502]])


In [9]:
# Step 6: Multiply weights with Values
output = torch.matmul(attn_weights, V)
print("Final attention output:\n", output)

Final attention output:
 tensor([[-0.0574,  0.9617,  0.1032, -0.2683],
        [-0.3320,  0.6441, -0.4338, -0.9378]])


In [10]:
K.shape[-1]

4